modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license="GNU GPL 3.0"
issueTrackerURL="https://github.com/Nick1st/FancyVideo-API/issues"
[[mods]]
modId = "fancyvideo_api"
version = "${version}"
displayName = "FancyVideo-API"
authors = "Nick1st"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fancyvideo-api"
logoFile="fancyvideo-api.png" #optional
credits="Thanks to the team behind VLC and Caprica for VLCJ, without them this mod wouldn't be possible. Also huge THANKS to Silk for helping me out with a few ideas, that made this finally possible. Huge thanks to Jared for making multi platform modding so easy." #optional
description = '''
A mod for rendering videos in minecraft.
'''
#logoFile = ""

[[dependencies.fancyvideo-api]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fancyvideo-api]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"
